// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Task_Tracker_API.Data;

#nullable disable

namespace Task_Tracker_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260314183531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Task_Tracker_API.Domain.BaseTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasDiscriminator<string>("TaskType").HasValue("BaseTask");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Task_Tracker_API.Domain.BugReportTask", b =>
                {
                    b.HasBaseType("Task_Tracker_API.Domain.BaseTask");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Bug");
                });

            modelBuilder.Entity("Task_Tracker_API.Domain.FeatureRequestTask", b =>
                {
                    b.HasBaseType("Task_Tracker_API.Domain.BaseTask");

                    b.Property<int>("EstimatedHours")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Feature");
                });
#pragma warning restore 612, 618
        }
    }
}
